services:
  - type: web
    name: bookstore-api
    runtime: node
    buildCommand: 'cd ./backend && npm ci --include=dev && npm run build && cd ..'
    startCommand: 'node ./backend/dist/server/server.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_KEY_PATH
        sync: false
